name: "Locale.API"

exports: "Locale.API.js"

web: "[mootools.net](http://mootools.net)"

description: "MooTools Localized API"

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; [MooTools](http://mootools.net)"

authors: "[MooTools Development Team](http://mootools.net/developers)"

sources:
  - "Source/Locale.API.js"
  - "Source/Locale.en-GB.API.js"
  - "Source/Locale.de-DE.API.js"
  - "Source/Locale.fr-FR.API.js"
  - "Source/Locale.it-IT.API.js"
  - "Source/Locale.nl-NL.API.js"
  - "Source/Locale.uk-UA.API.js"
